#ifndef CONFIG__HARDWARE_CONFIG_HPP_
#define CONFIG__HARDWARE_CONFIG_HPP_

// Center Arm
#define CENTER_ARM_RAISE_LOWER_SOLENOID_PIN 0
#define CENTER_ARM_EXTEND_RETRACT_SOLENOID_PIN 0

// Chassis
#define CHASSIS_OMNI_FL_MOTOR_MAG_PIN 0
#define CHASSIS_OMNI_FL_MOTOR_DIR_PIN 0
#define CHASSIS_OMNI_FR_MOTOR_MAG_PIN 0
#define CHASSIS_OMNI_FR_MOTOR_DIR_PIN 0
#define CHASSIS_OMNI_BL_MOTOR_MAG_PIN 0
#define CHASSIS_OMNI_BL_MOTOR_DIR_PIN 0
#define CHASSIS_OMNI_BR_MOTOR_MAG_PIN 0
#define CHASSIS_OMNI_BR_MOTOR_DIR_PIN 0

// Left Side Arm
#define LEFT_SIDE_ARM_SERVO_POTENTIOMETER_PIN 0
#define LEFT_SIDE_ARM_SERVO_MOTOR_MAG_PIN 0
#define LEFT_SIDE_ARM_SERVO_MOTOR_DIR_PIN 0
#define LEFT_SIDE_ARM_HAND_SOLENOID_PIN 0

// Right Side Arm
#define RIGHT_SIDE_ARM_SERVO_POTENTIOMETER_PIN 0
#define RIGHT_SIDE_ARM_SERVO_MOTOR_MAG_PIN 0
#define RIGHT_SIDE_ARM_SERVO_MOTOR_DIR_PIN 0
#define RIGHT_SIDE_ARM_HAND_SOLENOID_PIN 0

// T-Shirt Holder
#define T_SHIRT_HOLDER_SOLENOID_PIN 0

#endif
