#ifndef CONFIG__SOFTWARE_CONFIG_HPP_
#define CONFIG__SOFTWARE_CONFIG_HPP_

// Chassis
#define CHASSIS_OMNI_MAX_LINEAR_POWER 1.0
#define CHASSIS_OMNI_MAX_ANGULAR_POWER 1.0

// Side Arm ( Common )
#define SIDE_ARM_SERVO_PID_KP 0.0
#define SIDE_ARM_SERVO_PID_KI 0.0
#define SIDE_ARM_SERVO_PID_KD 0.0
#define SIDE_ARM_SERVO_PID_KB 0.0
#define SIDE_ARM_SERVO_PID_N 0.0
#define SIDE_ARM_SERVO_PID_T 0.0
#define SIDE_ARM_SERVO_PID_OUTPUT_MIN 0.0
#define SIDE_ARM_SERVO_PID_OUTPUT_MAX 0.0

// Left Side Arm
#define LEFT_SIDE_ARM_SERVO_EXTENDED_VALUE 0
#define LEFT_SIDE_ARM_SERVO_RETRACTED_VALUE 0
#define LEFT_SIDE_ARM_SERVO_HAND_OPEN_MIN_VALUE 0
#define LEFT_SIDE_ARM_SERVO_HAND_OPEN_MAX_VALUE 0

// Right Side Arm
#define RIGHT_SIDE_ARM_SERVO_EXTENDED_VALUE 0
#define RIGHT_SIDE_ARM_SERVO_RETRACTED_VALUE 0
#define RIGHT_SIDE_ARM_SERVO_HAND_OPEN_MIN_VALUE 0
#define RIGHT_SIDE_ARM_SERVO_HAND_OPEN_MAX_VALUE 0

#endif
