#include "config/config.hpp"
#include "robot.hpp"

#include <Arduino.h>

using ModuleConfig = module::ModuleConfig;

using CenterArmConfig = module::center_arm::CenterArmConfig;
using ChassisConfig = module::chassis::ChassisConfig;
using SideArmConfig = module::side_arm::SideArmConfig;
using TShirtHolderConfig = module::t_shirt_holder::TShirtHolderConfig;

using ServoConfig = cytron_servo::CytronServoConfig;
using OmniConfig = omni_4w::Omni4WConfig;

using MotorConfig = cytron_motor_driver_lib::MotorConfig;
using PIDConfig = simple_pid_lib::PIDConfig;

Robot robot(RobotConfig(ModuleConfig(
  CenterArmConfig(
    CENTER_ARM_RAISE_LOWER_SOLENOID_PIN, CENTER_ARM_EXTEND_RETRACT_SOLENOID_PIN,
    CENTER_ARM_RAISE_BUTTON, CENTER_ARM_LOWER_BUTTON, CENTER_ARM_EXTEND_BUTTON,
    CENTER_ARM_RETRACT_BUTTON),
  ChassisConfig(
    OmniConfig(
      MotorConfig(CHASSIS_OMNI_FL_MOTOR_MAG_PIN, CHASSIS_OMNI_FL_MOTOR_DIR_PIN),
      MotorConfig(CHASSIS_OMNI_FR_MOTOR_MAG_PIN, CHASSIS_OMNI_FR_MOTOR_DIR_PIN),
      MotorConfig(CHASSIS_OMNI_BL_MOTOR_MAG_PIN, CHASSIS_OMNI_BL_MOTOR_DIR_PIN),
      MotorConfig(CHASSIS_OMNI_BR_MOTOR_MAG_PIN, CHASSIS_OMNI_BR_MOTOR_DIR_PIN),
      CHASSIS_OMNI_MAX_LINEAR_POWER, CHASSIS_OMNI_MAX_ANGULAR_POWER),
    CHASSIS_LONGITUDINAL_AXIS, CHASSIS_LATERAL_AXIS, CHASSIS_ANGULAR_AXIS),
  SideArmConfig(
    ServoConfig(
      LEFT_SIDE_ARM_SERVO_POTENTIOMETER_PIN,
      MotorConfig(LEFT_SIDE_ARM_SERVO_MOTOR_MAG_PIN, LEFT_SIDE_ARM_SERVO_MOTOR_DIR_PIN),
      PIDConfig(
        SIDE_ARM_SERVO_PID_KP, SIDE_ARM_SERVO_PID_KI, SIDE_ARM_SERVO_PID_KD, SIDE_ARM_SERVO_PID_KB,
        SIDE_ARM_SERVO_PID_N, SIDE_ARM_SERVO_PID_T, SIDE_ARM_SERVO_PID_OUTPUT_MIN,
        SIDE_ARM_SERVO_PID_OUTPUT_MAX)),
    LEFT_SIDE_ARM_HAND_SOLENOID_PIN, LEFT_SIDE_ARM_ARM_BUTTON, LEFT_SIDE_ARM_HAND_BUTTON,
    LEFT_SIDE_ARM_SERVO_EXTENDED_VALUE, LEFT_SIDE_ARM_SERVO_RETRACTED_VALUE,
    LEFT_SIDE_ARM_SERVO_HAND_OPEN_MIN_VALUE, LEFT_SIDE_ARM_SERVO_HAND_OPEN_MAX_VALUE),
  SideArmConfig(
    ServoConfig(
      RIGHT_SIDE_ARM_SERVO_POTENTIOMETER_PIN,
      MotorConfig(RIGHT_SIDE_ARM_SERVO_MOTOR_MAG_PIN, RIGHT_SIDE_ARM_SERVO_MOTOR_DIR_PIN),
      PIDConfig(
        SIDE_ARM_SERVO_PID_KP, SIDE_ARM_SERVO_PID_KI, SIDE_ARM_SERVO_PID_KD, SIDE_ARM_SERVO_PID_KB,
        SIDE_ARM_SERVO_PID_N, SIDE_ARM_SERVO_PID_T, SIDE_ARM_SERVO_PID_OUTPUT_MIN,
        SIDE_ARM_SERVO_PID_OUTPUT_MAX)),
    RIGHT_SIDE_ARM_HAND_SOLENOID_PIN, RIGHT_SIDE_ARM_ARM_BUTTON, RIGHT_SIDE_ARM_HAND_BUTTON,
    RIGHT_SIDE_ARM_SERVO_EXTENDED_VALUE, RIGHT_SIDE_ARM_SERVO_RETRACTED_VALUE,
    RIGHT_SIDE_ARM_SERVO_HAND_OPEN_MIN_VALUE, RIGHT_SIDE_ARM_SERVO_HAND_OPEN_MAX_VALUE),
  TShirtHolderConfig(
    T_SHIRT_HOLDER_SOLENOID_PIN, T_SHIRT_HOLDER_EXTEND_BUTTON, T_SHIRT_HOLDER_RETRACT_BUTTON))));

void setup()
{
  robot.init();
}

void loop()
{
  robot.update();
}
